image: php:8.0-fpm

cache:
  paths:
    - vendor/

before_script:
  - apt-get update -yqq
  - apt-get install -yqq git zlib1g-dev libzip-dev libfreetype6-dev libjpeg62-turbo-dev libpng-dev libgmp-dev zlib1g-dev
  - docker-php-ext-configure gd --with-freetype --with-jpeg 
  - docker-php-ext-install gd 
  - docker-php-ext-install zip
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install

test:php80:
  script:
    - vendor/bin/phpunit --configuration phpunit.xml
